- name: "Extract files to ec2"
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: ./

- name: "install npm packages"
  become: true
  npm:
    name: install
    global: yes
    production: yes
    state: present

- name: "Stop pm2"
  become: true
  pm2:
    name: stop default
    global: yes
    production: yes
    state: present

- name: "Start pm2 service"
  become: true
  pm2:
    name: start npm -- start
    global: yes
    production: yes
    state: present
